grants/urls.py
from django.contrib import admin
from django.urls import path

import grants
from . import views

app_name = 'grant'

urlpatterns = [
    path("", views.all_grants, name='all_grants'),
    path('addnewgrant/', views.add_new_grant, name='add_new_grant'),
    path('grant/<int:grant_id>', views.specific_grant, name='specific_grant'),
    path('grant/<int:grant_id>/edit_grant', views.edit_grant, name='edit_grant'),
    path('grant/<int:grant_id>/delete_grant', views.delete_grant, name='delete_grant'),
    path('grant/<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money_in_grants, name='edit_sponsored_money_in_grants'),
    path('grant/<int:project_id>/delete_sponsored_money/<int:grant_id>', views.delete_sponsored_money_in_grants, name='delete_sponsored_money_in_grants'),
    path('grant/<int:grant_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),


]

junior_team/urls.py
from django.contrib import admin
from django.urls import path, include
import main_page
from main_page import views

urlpatterns = [
    path('', main_page.views.home, name='home'),
    path("admin/", admin.site.urls),

    path('teams/', include('teams.urls')),

    path('projects/', include('projects.urls')),

    path('grants/', include('grants.urls')),

    path('members/', include('members.urls')),

    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
]

members/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path("", views.all_members, name='all_members'),
    path('<int:member_id>/', views.specific_member, name='specific_member'),
    path('add_new_member/', views.add_new_member, name='add_new_member'),
    path('edit_member/<int:member_id>/', views.edit_member, name='edit_member'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member')
]

projects/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("", views.all_projects, name='all_projects'),
    path('addnewproject/', views.add_new_project, name='add_new_project'),
    path('<int:project_id>/', views.specific_project, name='specific_project'),
    path('<int:project_id>/delete', views.delete_project, name='delete_project'),
    path('<int:project_id>/edit', views.edit_project, name='edit_project'),
    path('<int:project_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),
    path('<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money, name='edit_sponsored_money'),

    # path('<int:blog_id>/', views.detail, name='detail')
]

teams/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path("", views.all_teams, name='all_teams'),
    path('<int:team_id>/', views.specific_team, name='specific_team'),
    path('add_new_team/', views.add_new_team, name='add_new_team'),
    path('edit_team/<int:team_id>/', views.edit_team, name='edit_team'),
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),
]

grants/forms.py
from django.forms import ModelForm

from projects.models import GrantModel, SponsoredMoneyModel


class NewGrantForm(ModelForm):
    class Meta:
        model = GrantModel
        fields = ['name']


class NewSponsoredMoneyForm(ModelForm):
    class Meta:
        model = SponsoredMoneyModel
        fields = ['project',
                  'money', ]

grants/views.py
from django.db.models import ProtectedError
from django.shortcuts import render, redirect

from grants.forms import NewGrantForm, NewSponsoredMoneyForm
from projects.models import SponsoredMoneyModel, ProjectModel, GrantModel
from projects.views import edit_sponsored_money, delete_sponsored_money


def all_grants(request):
    grants = GrantModel.objects.all()
    sponsored_money = SponsoredMoneyModel.objects.all()
    projects = ProjectModel.objects.all()
    return render(request, 'grants/all_grants.html', {'grants': grants, 'projects': projects,
                                                      'sponsored_money': sponsored_money})


def add_new_grant(request):
    if request.method == 'GET':
        return render(request, 'grants/add_new_grant.html', {'form': NewGrantForm})
    else:
        try:
            form = NewGrantForm(request.POST)  # создаем форму
            new_grant = form.save(commit=False)
            new_grant.save()
            return redirect('grant:all_grants')
        except ValueError:
            return render(request, 'grants/add_new_grant.html',
                          {'form': NewGrantForm(), 'error': 'Что-то заполнено не так'})
        except IndentationError:
            return render(request, 'grants/add_new_grant.html',
                          {'form': NewGrantForm(), 'error': 'Проект с таким названием уже существует'})


def specific_grant(request, grant_id):
    grant = GrantModel.objects.get(pk=grant_id)
    return render(request, 'grants/specific_grant.html', {'grant': grant, })


def add_sponsored_money(request, grant_id):
    if request.method == 'GET':
        return render(request, 'grants/add_sponsored_money.html', {'form': NewSponsoredMoneyForm})
    else:
        try:
            form = NewSponsoredMoneyForm(request.POST)  # создаем форму
            new_sponsored_money = form.save(commit=False)
            new_sponsored_money.grant = GrantModel.objects.get(pk=grant_id)
            new_sponsored_money.save()
            return redirect('grant:specific_grant', grant_id=grant_id)
        except ValueError:
            return render(request, 'grants/add_sponsored_money.html',
                          {'form': NewSponsoredMoneyForm(), 'error': 'Что-то заполнено не так'})
        except IndentationError:
            return render(request, 'grants/add_sponsored_money.html',
                          {'form': NewSponsoredMoneyForm(), 'error': 'Проект с таким названием уже существует'})


def edit_sponsored_money_in_grants(request, project_id, grant_id):
    to_page = f'grant:specific_grant'
    return edit_sponsored_money(request, project_id, grant_id, to_page)


def delete_sponsored_money_in_grants(request, project_id, grant_id):
    grant = GrantModel.objects.get(pk=grant_id)
    models = SponsoredMoneyModel.get_model_by_project_and_grant(project_id, grant_id)
    if not models:
        raise AssertionError("BEDA")
    sponsored_money = models[0]
    try:
        if request.method == 'POST':
            sponsored_money.delete()
            return redirect('grant:specific_grant', grant_id=grant_id)
        else:
            return render(request, 'grants/specific_grant.html', {'grant': grant})
    except Exception:
        return render(request, 'grants/specific_grant.html', {'grant': grant,
                                                              'error': 'почему-то не удаляется :(\n''айтишник посредственный оказался'})


def edit_grant(request, grant_id):
    grant = GrantModel.objects.get(pk=grant_id)
    if request.method == 'POST':
        form = NewGrantForm(request.POST, instance=grant)
        if form.is_valid():
            form.save()
            return redirect('grant:specific_grant', grant_id=grant_id)
    else:
        form = NewGrantForm(instance=grant)

    return render(request, 'grants/edit_grant.html', {'form': form, 'grant': grant, })


def delete_grant(request, grant_id):
    grant = GrantModel.objects.get(pk=grant_id)
    grants = GrantModel.objects.all()
    try:
        if request.method == 'POST':
            grant.delete()
            return redirect('grant:all_grants')
        else:
            return render(request, 'grants/all_grants.html', {'grants': grants})
    except ProtectedError:
        return render(request, 'grants/specific_grant.html',
                      {'grant': grant, 'error': 'Не удается удалить грант. Скорее всего это связано с тем, что есть проекты, связанные с этим грантом. Для того чтобы удалить грант, необходимо удалить все проекты, связанные с ним.'})
    except Exception:
        return render(request, 'grants/specific_grant.html',
                      {'grant': grant, 'error': 'почему-то не удаляется :(\n''айтишник посредственный оказался'})

grants/templates/grants/add_new_grant.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Add new grant</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
<form method="POST">
    {% csrf_token %}
    <h1>Новый грант</h1>

    <label for="name">Название:</label>
    {{ form.name }}

    <button type="submit">Добавить</button>
</form>
</body>

</html>

grants/templates/grants/add_sponsored_money.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Add sponsored money</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
<form method="POST">
    {% csrf_token %}
    <h1>Новый выигранный грант</h1>

    <label for="grant">Проект:</label>
    {{ form.project }}

    <label for="description">Выигранная сумма:</label>
    {{ form.money }}

    <button type="submit">Добавить</button>
</form>
</body>

</html>

grants/templates/grants/all_grants.html
<!-- your_template.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All grants</title>
    <!-- Добавьте стили для красивого оформления таблицы -->
    <style>
        .table-container {
            margin: 20px; /* Add margin around the table */
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        h2 {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        body, html {
        {#height: 100%;#} margin: 0;

            .container {
                display: flex;
                justify-content: space-around;
                align-items: center;
                height: 10vh;
                background: #dcdcdc; /* Light gray background */
            }

            .nav-link {
                color: #333; /* Dark gray text color */
                font-size: 18px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                padding: 10px 20px;
                border-radius: 5px;
                transition: background-color 0.3s;
            }

            .nav-link-custom {
            {#color: #333; /* Dark gray text color */#} font-size: 18px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                padding: 10px 20px;
                border-radius: 5px;
                transition: background-color 0.3s;
                background-color: #798083; /* Blue background */
                color: white; /* White text */
            }

            .nav-link:hover {
                background-color: #798083; /* Blue background on hover */
                color: white; /* White text on hover */

            }

            .nav-link {
                color: #333; /* Dark gray text color */
                font-size: 20px;
                font-family: Inter, serif;
                font-weight: 400;
                word-wrap: break-word;
            }

            .logout-btn {
                color: #333; /* Dark gray text color */
                font-size: 20px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                padding: 10px 20px;
                border-radius: 5px;
                border: none;
                background-color: transparent; /* Transparent background */
                transition: background-color 0.3s;
            }

            .logout-btn:hover {
                background-color: #798083; /* Red background on hover */
                color: white; /* White text on hover */
            }

            .add-btn {
                display: inline-block;
                padding: 7px 50px; /* Увеличенная ширина, уменьшенная высота */
                background-color: #798083; /* Более темный цвет фона */
                color: white; /* Белый текст */
                font-size: 18px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                border-radius: 5px;
                transition: background-color 0.3s;
                margin-left: 20px;
            }

            .add-btn:hover {
                background-color: #dcdcdc; /* Red background on hover */
                color: black; /* White text on hover */
            }
        }
    </style>
</head>
<body>
<div class="container">
    <a class="nav-link" href="{% url 'team:all_teams' %}">Советы</a>
    <a class="nav-link" href="{% url 'project:all_projects' %}">Проекты</a>
    <a class="nav-link-custom" href="{% url 'grant:all_grants' %}">Гранты</a>
    <a class="nav-link" href="{% url 'members:all_members' %}">Участники</a>
    {% if user.is_authenticated %}
        <form action="{% url 'logoutuser' %}" method="POST">
            {% csrf_token %}
            <input class="logout-btn" type="submit" value="Logout">
        </form>
    {% else %}
        <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
    {% endif %}
</div>
{#<h2>Информация по грантам</h2>#}
<h2>Общая сумма грантов по проектам: {{ grants.first.get_all_sponsored_money }}₽ </h2>
<div class="table-container">
    <table>
        <tr>
            <th></th>
            {% for project in projects %}
                <th><a href="{% url 'project:specific_project' project.id %}">{{ project.name }}</a></th>
            {% endfor %}
            <th>Итого</th>

        </tr>
        {% for grant in grants %}
            <tr>
                <th><a href="{% url 'grant:specific_grant' grant.id %}">{{ grant.name }}</a></th>
                {% for sum_ in grant.get_sponsored_money_for_all_projects.values %}
                    {% if sum_ == "не подавали" %}
                        <td>не подавали</td>
                    {% else %}
                        <td>{{ sum_ }}₽</td>
                    {% endif %}
                {% endfor %}
                <th>{{ grant.get_sponsored_money }}₽</th>
            </tr>
        {% endfor %}
        <th>Итого</th>
        {% for project in projects %}
            <th>{{ project.get_sponsored_money }}₽</th>
        {% endfor %}

        <div class="total">
            <th>{{ grants.first.get_all_sponsored_money }}₽</th>
        </div>
    </table>
</div>

<p>
    <a class="add-btn" href="{% url 'grant:add_new_grant' %}">Добавить грант</a>
</p>
</body>
</html>

grants/templates/grants/edit_grant.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Edit grant</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
<form method="POST">
    {% csrf_token %}
    <h1>Новый грант</h1>

    <label for="name">Название:</label>
    {{ form.name }}

    <button type="submit">Сохранить</button>
</form>
</body>

</html>

grants/templates/grants/specific_grant.html
<!-- your_template.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ grant.nameg }}</title>
    <style>
        .table-container {
            margin: 20px; /* Add margin around the table */
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        h2 {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        body, html {
            height: 100%;
            margin: 0;
        }

        .container2 {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 10vh;
            background: none;
        }

        .container2 a,
        .container2 form {
            margin: 10px; /* Убедимся, что внутренний отступ сброшен */
        }

        .container {
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 10vh;
            background: #dcdcdc; /* Light gray background */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .nav-link-custom {
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
            background-color: #798083; /* Blue background */
            color: white; /* White text */
        }

        .nav-link:hover {
            background-color: #798083; /* Blue background on hover */
            color: white; /* White text on hover */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            word-wrap: break-word;
        }

        .logout-btn {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            border: none;
            background-color: transparent; /* Transparent background */
            transition: background-color 0.3s;
        }

        .logout-btn:hover {
            background-color: #798083; /* Red background on hover */
            color: white; /* White text on hover */
        }

        .edit-btn,
        .delete-btn {
            display: inline;
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            margin-left: 20px;
            border: none;
            padding: 0;
            cursor: pointer;
            background: none;
            color: #798083;
        }

        .add-btn {
            display: inline-block;
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            margin-left: 20px;
            border: none;
            background-color: #798083; /* Transparent background */
            cursor: pointer;
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;

        }

        .add-btn:hover {
            background-color: #dcdcdc; /* Red background on hover */
            color: black; /* White text on hover */
        }


        .project-name {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .error-msg {
            color: red;
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
        }


    </style>
</head>


{% block content %}

    <div class="container">
        <a class="nav-link" href="{% url 'team:all_teams' %}">Советы</a>
        <a class="nav-link" href="{% url 'project:all_projects' %}">Проекты</a>
        <a class="nav-link-custom" href="{% url 'grant:all_grants' %}">Гранты</a>
        <a class="nav-link" href="{% url 'members:all_members' %}">Участники</a>
        {% if user.is_authenticated %}
            <form action="{% url 'logoutuser' %}" method="POST">
                {% csrf_token %}
                <input class="logout-btn" type="submit" value="Logout">
            </form>
        {% else %}
            <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
        {% endif %}
    </div>


    <div class="project-name">
        <h1>{{ grant.name }}</h1>
    </div>


    <body>
    {% if error %}
        <div class="error-msg">
            <h2>{{ error }}</h2>
        </div>
    {% endif %}
    {% if not grant.get_only_involved_projects.items %}
        <h2>Пока что ни один проект не был подан на этот грант.</h2>
    {% else %}
        <h2>Участвовашие проекты</h2>
        <div class="table-container">
            <table>
                <tr>
                    <th>Проект</th>
                    <th>Выигранная Сумма</th>
                    <th>Действия</th> <!-- Добавляем новую ячейку для действий -->
                </tr>
                {% for project, sum_ in grant.get_only_involved_projects.items %}
                    <tr>
                        <td><a href="{% url 'project:specific_project' project.id %}">{{ project.name }}</a></td>
                        <td>{{ sum_ }}₽</td>
                        <td>
                            <a class="edit-btn"
                               href="{% url 'grant:edit_sponsored_money_in_grants' project.id grant.id %}">✎</a>
                            <form class="delete-btn" method="POST"
                                  action="{% url 'grant:delete_sponsored_money_in_grants' project.id grant.id %}">
                                {% csrf_token %}
                                <button type="submit" class="edit-btn"> 🗑</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}
    <h2>
        <a class="add-btn" href="{% url 'grant:add_sponsored_money' grant.id %}">Добавить участвовавший проект</a>
    </h2>
    <br>
    <div class="container2">
        <a class="add-btn" href="{% url 'grant:edit_grant' grant.id %}">Редактировать название гранта</a>
        <form method="POST" action="{% url 'grant:delete_grant' grant.id %}">
            {% csrf_token %}
            <button type="submit" class="add-btn">Удалить грант</button>
        </form>
    </div>
    <p></p>
    </body>
{% endblock %}
</html>