grants/urls.py
from django.contrib import admin
from django.urls import path

import grants
from . import views

app_name = 'grant'

urlpatterns = [
    path("", views.all_grants, name='all_grants'),
    path('addnewgrant/', views.add_new_grant, name='add_new_grant'),
    path('grant/<int:grant_id>', views.specific_grant, name='specific_grant'),
    path('grant/<int:grant_id>/edit_grant', views.edit_grant, name='edit_grant'),
    path('grant/<int:grant_id>/delete_grant', views.delete_grant, name='delete_grant'),
    path('grant/<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money_in_grants, name='edit_sponsored_money_in_grants'),
    path('grant/<int:project_id>/delete_sponsored_money/<int:grant_id>', views.delete_sponsored_money_in_grants, name='delete_sponsored_money_in_grants'),
    path('grant/<int:grant_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),


]

junior_team/urls.py
from django.contrib import admin
from django.urls import path, include
import main_page
from main_page import views

urlpatterns = [
    path('', main_page.views.home, name='home'),
    path("admin/", admin.site.urls),

    path('teams/', include('teams.urls')),

    path('projects/', include('projects.urls')),

    path('grants/', include('grants.urls')),

    path('members/', include('members.urls')),

    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
]

members/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path("", views.all_members, name='all_members'),
    path('<int:member_id>/', views.specific_member, name='specific_member'),
    path('add_new_member/', views.add_new_member, name='add_new_member'),
    path('edit_member/<int:member_id>/', views.edit_member, name='edit_member'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member')
]

projects/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("", views.all_projects, name='all_projects'),
    path('addnewproject/', views.add_new_project, name='add_new_project'),
    path('<int:project_id>/', views.specific_project, name='specific_project'),
    path('<int:project_id>/delete', views.delete_project, name='delete_project'),
    path('<int:project_id>/edit', views.edit_project, name='edit_project'),
    path('<int:project_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),
    path('<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money, name='edit_sponsored_money'),

    # path('<int:blog_id>/', views.detail, name='detail')
]

teams/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path("", views.all_teams, name='all_teams'),
    path('<int:team_id>/', views.specific_team, name='specific_team'),
    path('add_new_team/', views.add_new_team, name='add_new_team'),
    path('edit_team/<int:team_id>/', views.edit_team, name='edit_team'),
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),
]

teams/forms.py
from django.forms import ModelForm

from projects.models import TeamModel


class NewTeamForm(ModelForm):
    class Meta:
        model = TeamModel
        fields = [
            'name',
            'vk_link',
            'manager',
            'person_from_gov',
            'person_from_company',
            'found_date',
        ]

teams/views.py
from django.db.models import ProtectedError
from django.shortcuts import render, get_object_or_404, redirect

from projects.models import TeamModel
from teams.forms import NewTeamForm


def all_teams(request):
    junior_teams = TeamModel.objects.all()
    return render(request, 'teams/all_teams.html', {'teams': junior_teams})


def specific_team(request, team_id):
    team = get_object_or_404(TeamModel, pk=team_id)
    return render(request, 'teams/specific_team.html', {'team': team})


def add_new_team(request):
    if request.method == 'GET':
        return render(request, 'teams/add_new_team.html', {'form': NewTeamForm})
    else:
        try:
            form = NewTeamForm(request.POST)
            new_project = form.save(commit=False)
            new_project.save()
            return redirect('team:all_teams')
        except ValueError:
            return render(request, 'teams/add_new_team.html',
                          {'form': NewTeamForm(), 'error': 'Что-то заполнено не так'})
        except IndentationError:
            return render(request, 'teams/add_new_team.html',
                          {'form': NewTeamForm(), 'error': 'Проект с таким названием уже существует'})


def edit_team(request, team_id):
    team = get_object_or_404(TeamModel, pk=team_id)
    if request.method == 'POST':
        form = NewTeamForm(request.POST, instance=team)
        if form.is_valid():
            form.save()
            return redirect('team:specific_team', team_id=team_id)
    else:
        form = NewTeamForm(instance=team)

    return render(request, 'teams/edit_team.html', {'form': form, 'team': team, })


def delete_team(request, team_id):
    team = get_object_or_404(TeamModel, pk=team_id)
    teams = TeamModel.objects.all()
    try:
        if request.method == 'POST':
            team.delete()
            return redirect('team:all_teams')
        else:
            return render(request, 'teams/all_teams.html', {'teams': teams})
    except Exception:
        return render(request, 'teams/specific_team.html', {'team': team, 'error': 'Ошибка при удалении команды. Скорее всего, это связно с тем, что есть проекты, которые ею реализуются, а также участники, которые в ней состоят. Чтобы удалить команду необходимо, необходимо удалить все проекты, которые ею реализуются, а также всех участников, которые в ней состоят.'})

teams/templates/teams/add_new_team.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Add new team</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
<form method="POST">
    {% csrf_token %}
    <h1>Новый совет</h1>

    <label for="name">Название:</label>
    <input type="text" id="name" name="name" required>

    <label for="by_team">Ссылка на сообщество:</label>
    {{ form.vk_link }}

    <label for="manager">Председатель:</label>
    {{ form.manager }}

    <label for="period_type">Представитель от администрации:</label>
    {{ form.person_from_gov }}

    <label for="period_type">Представитель от предприятия:</label>
    {{ form.person_from_company }}

    <label for="found_date" id="endDateLabel">Дата основания:</label>
    <input type="date" id="found_date" name="found_date">

    <button type="submit">Добавить</button>
</form>
</body>

</html>

teams/templates/teams/all_teams.html
{% load static %}
<!-- your_template.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teams</title>
    <!-- Добавьте стили для красивого оформления таблицы -->
    <style>
        .table-container {
            margin: 20px; /* Add margin around the table */
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        h2 {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        body, html {
        {#height: 100%;#} margin: 0;

            .container {
                display: flex;
                justify-content: space-around;
                align-items: center;
                height: 10vh;
                background: #dcdcdc; /* Light gray background */
            }

            .nav-link {
                color: #333; /* Dark gray text color */
                font-size: 18px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                padding: 10px 20px;
                border-radius: 5px;
                transition: background-color 0.3s;
            }

            .nav-link-custom {
            {#color: #333; /* Dark gray text color */#} font-size: 18px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                padding: 10px 20px;
                border-radius: 5px;
                transition: background-color 0.3s;
                background-color: #798083; /* Blue background */
                color: white; /* White text */
            }

            .nav-link:hover {
                background-color: #798083; /* Blue background on hover */
                color: white; /* White text on hover */

            }

            .nav-link {
                color: #333; /* Dark gray text color */
                font-size: 20px;
                font-family: Inter, serif;
                font-weight: 400;
                word-wrap: break-word;
            }

            .logout-btn {
                color: #333; /* Dark gray text color */
                font-size: 20px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                padding: 10px 20px;
                border-radius: 5px;
                border: none;
                background-color: transparent; /* Transparent background */
                transition: background-color 0.3s;
            }

            .logout-btn:hover {
                background-color: #798083; /* Red background on hover */
                color: white; /* White text on hover */
            }

            .add-btn {
                display: inline-block;
                padding: 7px 50px; /* Увеличенная ширина, уменьшенная высота */
                background-color: #798083; /* Более темный цвет фона */
                color: white; /* Белый текст */
                font-size: 18px;
                font-family: Inter, serif;
                font-weight: 400;
                text-decoration: none;
                border-radius: 5px;
                transition: background-color 0.3s;
                margin-left: 20px;
            }

            .add-btn:hover {
                background-color: #368c3a; /* Darker green background on hover */
            }
        }
    </style>
</head>
{% block content %}
    <div class="container">
        <a class="nav-link-custom" href="{% url 'team:all_teams' %}">Советы</a>
        <a class="nav-link" href="{% url 'project:all_projects' %}">Проекты</a>
        <a class="nav-link" href="{% url 'grant:all_grants' %}">Гранты</a>
        <a class="nav-link" href="{% url 'members:all_members' %}">Участники</a>
        {% if user.is_authenticated %}
            <form action="{% url 'logoutuser' %}" method="POST">
                {% csrf_token %}
                <input class="logout-btn" type="submit" value="Logout">
            </form>
        {% else %}
            <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
        {% endif %}
    </div>
    <body>
    <h2>Советы</h2>
    <div class="table-container">
        <table>
            <tr>
                <th>Название</th>
                <th>Председатель</th>
                <th>Количество участников</th>
                <th>Дата основания</th>
                <th>Ссылка</th>
            </tr>
            {% for item in teams %}
                <tr>
                    <td><a href="{% url 'team:specific_team' item.id %}">{{ item.name }}</a></td>
                    <td>{{ item.manager }}</td>
                    <td>{{ item.get_member_num }}</td>
                    {% if  item.found_date %}
                        <td>{{ item.found_date|date:'d.m.Y' }}</td>
                    {% else %}
                        <td>-</td>
                    {% endif %}
                    {% if item.vk_link %}
                        <td><a href="{{ item.vk_link }}">{{ item.vk_link }}</a></td>
                    {% else %}
                        <td>-</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <p>
        <a class="add-btn" href="{% url 'team:add_new_team' %}">Добавить совет</a>
    </p>
    </body>
{% endblock %}
</html>

teams/templates/teams/edit_team.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Edit team</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
<form method="POST">
    {% csrf_token %}
    <h1>Редактировать информацию о совете</h1>

    <label for="name">Название:</label>
    {{ form.name }}

    <label for="by_team">Ссылка на сообщество:</label>
    {{ form.vk_link }}

    <label for="manager">Председатель:</label>
    {{ form.manager }}

    <label for="period_type">Представитель от администрации:</label>
    {{ form.person_from_gov }}

    <label for="period_type">Представитель от предприятия:</label>
    {{ form.person_from_company }}

    <label for="found_date" id="endDateLabel">Дата основания:</label>
    <input type="date" id="found_date" name="found_date">

    <button type="submit" value="Save">Сохранить</button>
</form>
</body>

</html>

teams/templates/teams/specific_team.html
<!-- your_template.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ team.name }}</title>
    <style>
        .table-container {
            margin: 20px; /* Add margin around the table */
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        h2 {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        body, html {
        {#height: 100%;#} margin: 0;
        }

        .container {
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 10vh;
            background: #dcdcdc; /* Light gray background */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .nav-link-custom {
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
            background-color: #798083; /* Blue background */
            color: white; /* White text */
        }

        .nav-link:hover {
            background-color: #798083; /* Blue background on hover */
            color: white; /* White text on hover */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            word-wrap: break-word;
        }

        .logout-btn {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            border: none;
            background-color: transparent; /* Transparent background */
            transition: background-color 0.3s;
        }

        .logout-btn:hover {
            background-color: #798083; /* Red background on hover */
            color: white; /* White text on hover */
        }

        .add-btn {
            display: inline-block;
            padding: 7px 50px; /* Увеличенная ширина, уменьшенная высота */
            background-color: #798083; /* Более темный цвет она */
            color: white; /* Белый текст */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin-left: 20px;
        }

        .delete-btn {
            display: inline-block;
            padding: 7px 50px; /* Увеличенная ширина, уменьшенная высота */
            background-color: #798083; /* Более темный цвет она */
            color: white; /* Белый текст */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin-left: 20px;
            border: none;
        }

        .delete-btn:hover,
        .add-btn:hover {
            background-color: #dcdcdc; /* Red background on hover */
            color: black; /* White text on hover */
        }

        .project-name {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .project-grants-info {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: left;
            margin-left: 20px;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .error-message {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
            color: red;
        }

    </style>
</head>


{% block content %}

    <div class="container">
        <a class="nav-link-custom" href="{% url 'team:all_teams' %}">Советы</a>
        <a class="nav-link" href="{% url 'project:all_projects' %}">Проекты</a>
        <a class="nav-link" href="{% url 'grant:all_grants' %}">Гранты</a>
        <a class="nav-link" href="{% url 'members:all_members' %}">Участники</a>
        {% if user.is_authenticated %}
            <form action="{% url 'logoutuser' %}" method="POST">
                {% csrf_token %}
                <input class="logout-btn" type="submit" value="Logout">
            </form>
        {% else %}
            <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
        {% endif %}
    </div>


    <div class="project-name">
        <h1>{{ team.name }}</h1>
    </div>

    <body>
    <br>
    <h2>Общая информация</h2>
    <div class="table-container">
        <table>
            <tr>
                <th>Председатель</th>
                <th>Количество участников</th>
                <th>Представитель от администрации</th>
                <th>Представитель от предприятия</th>
                <th>Дата основания</th>
                <th>Ссылка</th>
            </tr>
            <tr>
                <td>{{ team.manager }}</td>
                <td>{{ team.get_member_num }}</td>
                <td>{{ team.person_from_gov }}</td>
                <td>{{ team.person_from_company }}</td>
                <td>{{ team.found_date|date:'d.m.Y' }}</td>
                <td><a href="{{ team.vk_link }}">{{ team.vk_link }}</a></td>
            </tr>
        </table>
    </div>

    <p>
        <a class="add-btn" href="{% url 'team:edit_team' team.id %}">Редактировать</a>
    </p>
    <form method="POST" action="{% url 'team:delete_team' team.id %}">
        {% csrf_token %}
        <button type="submit" class="delete-btn">Удалить</button>
        {#        <button class="delete-btn" href="{% url 'team:delete_team' team.id %}">Удалить</button>#}
    </form>

    {% if error %}
        <div class="error-message"><p>{{ error }}</p></div>
    {% endif %}

    <br>
    <h2>Реализуемые проекты</h2>
    {% if not team.get_running_projects %}

        <div class="project-grants-info">
            <p>У данного совета нет текущих проектов</p>
        </div>
    {% else %}
        <div class="table-container">
            <table>
                <tr>
                    <th>Проект</th>
                    <th>Средств получено</th>
                    <th>Статус</th>
                </tr>
                {% for project in team.get_running_projects %}
                    <tr>
                        <td><a href="{% url 'project:specific_project' project.id %}">{{ project.name }}</a></td>
                        <td>{{ project.get_sponsored_money }}₽</td>
                        {% if project.status %}
                            <td>Завершен</td>
                        {% else %}
                            <td>В реализации</td>
                        {% endif %}

                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}
    <br>

    <h2>Участники совета</h2>
    <div class="table-container">
        <table>
            <tr>
                <th>Имя</th>
                <th>tg</th>
            </tr>
            {% for member in team.get_members %}
                <tr>
                    <td>
                        <a href="{% url 'members:specific_member' member.id %}">{{ member.get_full_name }}</a>
                    </td>
                    <td>
                        <a href="https://t.me/{{ member.get_username }}" target="_blank">{{ member.tg_username }}</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <p></p>
    </body>
{% endblock %}
</html>