grants/urls.py
from django.contrib import admin
from django.urls import path

import grants
from . import views

app_name = 'grant'

urlpatterns = [
    path("", views.all_grants, name='all_grants'),
    path('addnewgrant/', views.add_new_grant, name='add_new_grant'),
    path('grant/<int:grant_id>', views.specific_grant, name='specific_grant'),
    path('grant/<int:grant_id>/edit_grant', views.edit_grant, name='edit_grant'),
    path('grant/<int:grant_id>/delete_grant', views.delete_grant, name='delete_grant'),
    path('grant/<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money_in_grants, name='edit_sponsored_money_in_grants'),
    path('grant/<int:project_id>/delete_sponsored_money/<int:grant_id>', views.delete_sponsored_money_in_grants, name='delete_sponsored_money_in_grants'),
    path('grant/<int:grant_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),


]

junior_team/urls.py
from django.contrib import admin
from django.urls import path, include
import main_page
from main_page import views

urlpatterns = [
    path('', main_page.views.home, name='home'),
    path("admin/", admin.site.urls),

    path('teams/', include('teams.urls')),

    path('projects/', include('projects.urls')),

    path('grants/', include('grants.urls')),

    path('members/', include('members.urls')),

    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
]

members/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path("", views.all_members, name='all_members'),
    path('<int:member_id>/', views.specific_member, name='specific_member'),
    path('add_new_member/', views.add_new_member, name='add_new_member'),
    path('edit_member/<int:member_id>/', views.edit_member, name='edit_member'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member')
]

projects/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("", views.all_projects, name='all_projects'),
    path('addnewproject/', views.add_new_project, name='add_new_project'),
    path('<int:project_id>/', views.specific_project, name='specific_project'),
    path('<int:project_id>/delete', views.delete_project, name='delete_project'),
    path('<int:project_id>/edit', views.edit_project, name='edit_project'),
    path('<int:project_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),
    path('<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money, name='edit_sponsored_money'),

    # path('<int:blog_id>/', views.detail, name='detail')
]

teams/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path("", views.all_teams, name='all_teams'),
    path('<int:team_id>/', views.specific_team, name='specific_team'),
    path('add_new_team/', views.add_new_team, name='add_new_team'),
    path('edit_team/<int:team_id>/', views.edit_team, name='edit_team'),
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),
]

members/forms.py
from django.forms import ModelForm, inlineformset_factory
from django import forms

from projects.models import TeamModel, MemberModel


class NewMemberForm(ModelForm):
    class Meta:
        model = MemberModel
        fields = [
            'first_name',
            'second_name',
            'last_name',
            'status',
            'team',
            'email',
            'phone',
            'tg_username',
            'date_of_birth',
            'city',
            'school',
            'grade',
            'languages',
            'subjects',
            'skills',
            'hobbies',
            'achievements',
            'more_info',
        ]

members/views.py
from django.shortcuts import render, get_object_or_404, redirect

from members.forms import NewMemberForm
from projects.models import MemberModel, TeamModel


# def all_teams(request):
#     junior_teams = TeamModel.objects.all()
#     return render(request, 'teams/all_teams.html', {'teams': junior_teams})


def all_members(request):
    members = MemberModel.objects.all()
    teams = TeamModel.objects.all()
    return render(request, 'members/all_members.html', {'members': members, 'teams': teams})


# def specific_team(request, team_id):
#     team = get_object_or_404(TeamModel, pk=team_id)
#     return render(request, 'teams/specific_team.html', {'team': team})

def specific_member(request, member_id):
    member = get_object_or_404(MemberModel, pk=member_id)
    return render(request, 'members/specific_member.html', {'member': member})


def add_new_member(request):
    if request.method == 'GET':
        return render(request, 'members/add_new_member.html', {'form': NewMemberForm})
    else:
        form = NewMemberForm(request.POST)
        if form.is_valid():
            new_member = form.save(commit=False)
            new_member.save()
            return redirect('members:all_members')
        else:
            return render(request, 'members/add_new_member.html',
                          {'form': NewMemberForm(), 'error': form.errors})


def edit_member(request, member_id):
    member = get_object_or_404(MemberModel, pk=member_id)
    if request.method == 'POST':
        form = NewMemberForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            return redirect('members:specific_member', member_id=member_id)
    else:
        form = NewMemberForm(instance=member)

    return render(request, 'members/edit_member.html', {'form': form, 'member': member})


def delete_member(request, member_id):
    member = get_object_or_404(MemberModel, pk=member_id)
    members = MemberModel.objects.all()
    try:
        if request.method == 'POST':
            member.delete()
            return redirect('members:all_members')
    except Exception as e:
        return render(request, 'members/specific_member.html', {'member': member,
                                                                'error': 'почему-то не удаляется :(\n''айтишник посредственный оказался'})
    return render(request, 'members/all_members.html', {'members': members})

members/templates/members/add_new_member.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Add new member</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }

    </style>
</head>


<body>
<form method="POST">
    {% csrf_token %}
    {{ error }}
    <h1>Новый участник</h1>

    <label for="first_name">Имя:</label>
    {{ form.first_name }}

    <label for="second_name">Отчество:</label>
    {{ form.second_name }}

    <label for="last_name">Фамилия:</label>
    {{ form.last_name }}

    <label for="date_of_birth" id="endDateLabel">Дата рождения:</label>
    <input type="date" id="date_of_birth" name="date_of_birth">

    <label for="status">Школьник/Студент:</label>
    {{ form.status }}

    <label for="team">Представителем какого совета вы являетесь:</label>
    {{ form.team }}

    <label for="email">Email:</label>
    {{ form.email }}

    <label for="phone">Телефон:</label>
    <input id="phone" name="phone" required placeholder="+79991829028">
    {#    {{ form.phone }}#}

    <label for="tg_username">Telegram:</label>
    <input id="tg_username" name="tg_username" required placeholder="@arseny_volodko">
    {#    {{ form.tg_username }}#}

    <label for="city">Город проживания:</label>
    {{ form.city }}

    <label for="school">Школа/ВУЗ:</label>
    {{ form.school }}

    <label for="grade">Класс/Курс:</label>
    {{ form.grade }}

    <label for="languages">Иностранные языки</label>
    <textarea id="languages" name="languages" rows="4" required placeholder=
            "Русский - родной
Английский - B2
Испанский - A2
..."></textarea>

    <label for="subjects">Интересующие предметы:</label>
    {{ form.subjects }}

    <label for="skills">Расскажите о своих навыках, умениях:</label>
    <textarea id="skills" name="skills" rows="4" required placeholder="Управление проектами
Верстка сайтов
..."></textarea>

    <label for="hobbies">Расскажите о своих увлечениях:</label>
    {{ form.hobbies }}

    <label for="achievements">Расскажите о своих достижениях:</label>
    <textarea id="achievements" name="achievements" rows="4" required placeholder="Победитель Большой перемены - 2020г
Победитель заключительного этапа ВСОШ по информатике - 2021г
..."></textarea>

    <label for="more_info">Напишите здесь о себе все, что хотите. Не стесняйтесь:</label>
    <textarea id="more_info" name="more_info" rows="4" required placeholder="Владение английским - B2
..."></textarea>

    <button type="submit">Добавить</button>
</form>

</body>

</html>

members/templates/members/all_members.html
<!-- your_template.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All members</title>
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }

        .container {
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 10vh;
            background: #dcdcdc; /* Light gray background */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .nav-link-custom {
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
            background-color: #798083; /* Blue background */
            color: white; /* White text */
        }

        .nav-link:hover {
            background-color: #798083; /* Blue background on hover */
            color: white; /* White text on hover */
        }

        .logout-btn {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            border: none;
            background-color: transparent; /* Transparent background */
            transition: background-color 0.3s;
        }

        .logout-btn:hover {
            background-color: #798083; /* Red background on hover */
            color: white; /* White text on hover */
        }

        .add-btn {
            display: inline-block;
            padding: 7px 50px;
            background-color: #798083;
            color: white;
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin: 0 auto; /* Добавьте эту строку для выравнивания по центру */
            text-align: center;
        }

        .add-btn:hover {
            background-color: #dcdcdc; /* Цвет фона при наведении */
            color: #333; /* Черный текст при наведении */
        }

        h2 {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .project-manager {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            margin-left: 20px;
            margin-top: 20px;
        }

        .table-container {
            margin: 20px;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 10px; /* Add some space above the table */
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            width: 150px; /* Set a fixed width for the columns */
        }

        th {
            background-color: #f2f2f2;
        }

        .accordion {
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            transition: 0.4s;
        }

        .active, .accordion:hover {
            background-color: #ccc;
        }

        .panel {
            padding: 0 18px;
            display: none;
            background-color: white;
            overflow: hidden;
        }
    </style>
</head>

<body>
<div class="container">
    <a class="nav-link" href="{% url 'team:all_teams' %}">Советы</a>
    <a class="nav-link" href="{% url 'project:all_projects' %}">Проекты</a>
    <a class="nav-link" href="{% url 'grant:all_grants' %}">Гранты</a>
    <a class="nav-link-custom" href="{% url 'members:all_members' %}">Участники</a>
    {% if user.is_authenticated %}
        <form action="{% url 'logoutuser' %}" method="POST">
            {% csrf_token %}
            <input class="logout-btn" type="submit" value="Logout">
        </form>
    {% else %}
        <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
    {% endif %}
</div>

<h2>Участники советов (Итого: {{ members.count }})</h2>
<h2><a class="add-btn" href="{% url 'members:add_new_member' %}">Добавить участника</a></h2>

{% for team in teams %}
    <button class="accordion">{{ team.name }} ({{ team.get_member_num }} участников)</button>
    <div class="panel">
        <div class="table-container">
            <table>
                <tr>
                    <th>ФИО</th>
                    <th>Город</th>
                    <th>tg</th>
                </tr>
                {% for member in team.get_members %}
                    <tr>
                        <td><a href="{% url 'members:specific_member' member.id %}">{{ member.get_full_name }}</a></td>
                        <td>{{ member.city }}</td>
                        <td><a href="https://t.me/{{ member.get_username }}"
                               target="_blank">{{ member.tg_username }}</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endfor %}

<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>
</body>

</html>

members/templates/members/edit_member.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Edit member</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }

    </style>
</head>


<body>
<form method="POST">
    {% csrf_token %}
    {{ error }}
    <h1>Новый участник</h1>

    <label for="first_name">Имя:</label>
    {{ form.first_name }}

    <label for="second_name">Отчество:</label>
    {{ form.second_name }}

    <label for="last_name">Фамилия:</label>
    {{ form.last_name }}

    <label for="date_of_birth" id="endDateLabel">Дата рождения:</label>
    <input type="date" id="date_of_birth" name="date_of_birth" value="{{ member.date_of_birth|date:'Y-m-d' }}" required>

    <label for="status">Школьник/Студент:</label>
    {{ form.status }}

    <label for="team">Представителем какого совета вы являетесь:</label>
    {{ form.team }}

    <label for="email">Email:</label>
    {{ form.email }}

    <label for="phone">Телефон:</label>
    {{ form.phone }}

    <label for="tg_username">Telegram:</label>
    {{ form.tg_username }}

    <label for="city">Город проживания:</label>
    {{ form.city }}

    <label for="school">Школа/ВУЗ:</label>
    {{ form.school }}

    <label for="grade">Класс/Курс:</label>
    {{ form.grade }}

    <label for="languages">Иностранные языки</label>
    {{ form.languages }}

    <label for="subjects">Интересующие предметы:</label>
    {{ form.subjects }}

    <label for="skills">Расскажите о своих навыках, умениях:</label>
    {{ form.skills }}

    <label for="hobbies">Расскажите о своих увлечениях:</label>
    {{ form.hobbies }}

    <label for="achievements">Расскажите о своих достижениях:</label>
    {{ form.achievements }}


    <label for="more_info">Напишите здесь о себе все, что хотите. Не стесняйтесь:</label>
    {{ form.more_info }}

    <button type="submit">Сохранить</button>
</form>

</body>

</html>

members/templates/members/specific_member.html
<!-- your_template.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ member.get_full_name }}</title>
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }

        .error-msg {
            color: red;
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
        }

        .container {
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 10vh;
            background: #dcdcdc; /* Light gray background */
        }

        .container2 {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 10vh;
            background: none;
        }

        .container2 a,
        .container2 form {
            margin: 10px; /* Убедимся, что внутренний отступ сброшен */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .nav-link-custom {
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
            background-color: #798083; /* Blue background */
            color: white; /* White text */
        }

        .nav-link:hover {
            background-color: #798083; /* Blue background on hover */
            color: white; /* White text on hover */
        }

        .logout-btn {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            border: none;
            background-color: transparent; /* Transparent background */
            transition: background-color 0.3s;
        }

        .logout-btn:hover {
            background-color: #798083; /* Red background on hover */
            color: white; /* White text on hover */
        }

        .add-btn {
            display: inline-block;
            padding: 7px 50px;
            background-color: #798083;
            color: white;
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin: 0 auto; /* Добавьте эту строку для выравнивания по центру */
            text-align: center;
            border: none;
        }

        .add-btn:hover {
            background-color: #dcdcdc; /* Цвет фона при наведении */
            color: #333; /* Черный текст при наведении */
        }

        h2 {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .project-manager {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            margin-left: 20px;
            margin-top: 20px;
        }

        .table-container {
            margin: 20px;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 10px; /* Add some space above the table */
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            width: 150px; /* Set a fixed width for the columns */
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
<div class="container">
    <a class="nav-link" href="{% url 'team:all_teams' %}">Советы</a>
    <a class="nav-link" href="{% url 'project:all_projects' %}">Проекты</a>
    <a class="nav-link" href="{% url 'grant:all_grants' %}">Гранты</a>
    <a class="nav-link-custom" href="{% url 'members:all_members' %}">Участники</a>
    {% if user.is_authenticated %}
        <form action="{% url 'logoutuser' %}" method="POST">
            {% csrf_token %}
            <input class="logout-btn" type="submit" value="Logout">
        </form>
    {% else %}
        <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
    {% endif %}
</div>

<h2>{{ member.get_full_name }}</h2>
<div class="error-msg">
    {% if error %}
        {{ error }}
        {{ form.errors }}
    {% endif %}
</div>
<div class="table-container">
    <table>
        <tr>
            <th>поле</th>
            <th>инфо</th>
        </tr>
        <th>tg</th>
        <td><a href="https://t.me/{{ member.get_username }}" target="_blank">{{ member.tg_username }}</a></td>
        {% for field, value in member.get_all_info.items %}
            <tr>
                <th>{{ field }}</th>
                {% if value %}
                    {% if value|date %}
                        <td>{{ value|date:"d.m.Y" }}</td>
                    {% else %}
                        <td>{{ value|linebreaksbr }}</td>
                    {% endif %}
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>

<div class="container2">
    <a class="add-btn" href="{% url 'members:edit_member' member.id %}">Редактировать информацию</a>
    <form method="POST" action="{% url 'members:delete_member' member.id %}">
        {% csrf_token %}
        <button type="submit" class="add-btn">Удалить участника</button>
    </form>
</div>
</body>
</html>