grants/urls.py
from django.contrib import admin
from django.urls import path

import grants
from . import views

app_name = 'grant'

urlpatterns = [
    path("", views.all_grants, name='all_grants'),
    path('addnewgrant/', views.add_new_grant, name='add_new_grant'),
    path('grant/<int:grant_id>', views.specific_grant, name='specific_grant'),
    path('grant/<int:grant_id>/edit_grant', views.edit_grant, name='edit_grant'),
    path('grant/<int:grant_id>/delete_grant', views.delete_grant, name='delete_grant'),
    path('grant/<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money_in_grants, name='edit_sponsored_money_in_grants'),
    path('grant/<int:project_id>/delete_sponsored_money/<int:grant_id>', views.delete_sponsored_money_in_grants, name='delete_sponsored_money_in_grants'),
    path('grant/<int:grant_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),


]

junior_team/urls.py
from django.contrib import admin
from django.urls import path, include
import main_page
from main_page import views

urlpatterns = [
    path('', main_page.views.home, name='home'),
    path("admin/", admin.site.urls),

    path('teams/', include('teams.urls')),

    path('projects/', include('projects.urls')),

    path('grants/', include('grants.urls')),

    path('members/', include('members.urls')),

    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
]

members/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path("", views.all_members, name='all_members'),
    path('<int:member_id>/', views.specific_member, name='specific_member'),
    path('add_new_member/', views.add_new_member, name='add_new_member'),
    path('edit_member/<int:member_id>/', views.edit_member, name='edit_member'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member')
]

projects/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("", views.all_projects, name='all_projects'),
    path('addnewproject/', views.add_new_project, name='add_new_project'),
    path('<int:project_id>/', views.specific_project, name='specific_project'),
    path('<int:project_id>/delete', views.delete_project, name='delete_project'),
    path('<int:project_id>/edit', views.edit_project, name='edit_project'),
    path('<int:project_id>/add_sponsored_money', views.add_sponsored_money, name='add_sponsored_money'),
    path('<int:project_id>/edit_sponsored_money/<int:grant_id>', views.edit_sponsored_money, name='edit_sponsored_money'),

    # path('<int:blog_id>/', views.detail, name='detail')
]

teams/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path("", views.all_teams, name='all_teams'),
    path('<int:team_id>/', views.specific_team, name='specific_team'),
    path('add_new_team/', views.add_new_team, name='add_new_team'),
    path('edit_team/<int:team_id>/', views.edit_team, name='edit_team'),
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),
]

projects/models.py
from django.db import models
from django.db.models import Sum


# from projects.models import ProjectModel

class TeamModel(models.Model):
    name = models.CharField()
    vk_link = models.URLField(blank=True, null=True)
    person_from_gov = models.CharField(blank=True, null=True)
    person_from_company = models.CharField(blank=True, null=True)
    found_date = models.DateField(blank=True, null=True)
    manager = models.CharField(blank=True, null=True)

    def get_member_num(self):
        return MemberModel.objects.filter(team__name=self.name).count()

    def get_members(self):
        return MemberModel.objects.filter(team__name=self.name)

    def get_running_projects(self):
        return ProjectModel.objects.filter(by_team__name=self.name)

    def __str__(self):
        return self.name


class ProjectModel(models.Model):
    PERIOD_TYPE_CHOICES = [
        ('долгосрочный', 'долгосрочный'),
        ('краткосрочный', 'краткосрочный'),
    ]

    name = models.CharField(unique=True)
    description = models.CharField()
    by_team = models.ForeignKey(TeamModel, on_delete=models.PROTECT)
    manager = models.CharField(blank=True, null=True)
    author = models.CharField(blank=True, null=True)
    period_type = models.CharField(max_length=20, choices=PERIOD_TYPE_CHOICES)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    status = models.BooleanField(default=False)

    def get_fields(self):
        return [i for i in self._meta.fields]

    def get_fields_strings(self):
        return {
            'name': "Название проекта",
            'description': "Описание проекта",
            'by_team': "Совет-реализатор",
            'manager': "Автор проекта",
            'period_type': "Долгосрочный/краткосрочный",
            'start_date': "Дата реализации",
            'end_date': "Дата завершения",
        }

    def __str__(self):
        return self.name

    def get_sponsored_money(self):
        # if grant_name:
        #     res = SponsoredMoneyModel.objects.filter(project__name=self.name, grant__name=grant_name).aggregate(Sum('money')).get('money__sum', 0)
        # else:
        res = SponsoredMoneyModel.objects.filter(project__name=self.name).aggregate(Sum('money')).get('money__sum', 0.0)
        return res if res is not None else 0.0

    def get_sponsored_money_from_specific_grant(self, grant_name):
        res = SponsoredMoneyModel.objects.filter(project__name=self.name, grant__name=grant_name).aggregate(
            Sum('money')).get('money__sum', 0.0)
        return res if res is not None else "не подавали"

    def get_sponsored_money_from_all_grants(self):
        grants = GrantModel.objects.all()
        return {grant: self.get_sponsored_money_from_specific_grant(grant.name) for grant in grants}


class GrantModel(models.Model):
    name = models.CharField(unique=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_all_grants():
        return GrantModel.objects.all()

    @staticmethod
    def get_all_sponsored_money():
        res = SponsoredMoneyModel.objects.all().aggregate(Sum('money')).get('money__sum', 0.0)
        return res if res is not None else 0.0

    def get_sponsored_money(self):
        res = SponsoredMoneyModel.objects.filter(grant__name=self.name).aggregate(Sum('money')).get('money__sum', 0.0)
        return res if res is not None else 0.0

    def get_sponsored_money_for_specific_project(self, project_name):
        res = SponsoredMoneyModel.objects.filter(project__name=project_name, grant__name=self.name).aggregate(
            Sum('money')).get('money__sum', 0.0)
        return res if res is not None else "не подавали"

    def get_sponsored_money_for_all_projects(self):
        projects = ProjectModel.objects.all()
        return {project.name: self.get_sponsored_money_for_specific_project(project.name) for project in projects}

    def get_only_involved_projects(self):
        projects = ProjectModel.objects.all()
        res = {}
        for project in projects:
            val = self.get_sponsored_money_for_specific_project(project.name)
            if val != 'не подавали':
                res[project] = val
        return res


class SponsoredMoneyModel(models.Model):
    project = models.ForeignKey(ProjectModel, on_delete=models.PROTECT)
    money = models.FloatField()
    grant = models.ForeignKey(GrantModel, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.project.name} - {self.grant.name} - {self.money}'

    @staticmethod
    def get_model_by_project_and_grant(project_id, grant_id):
        return SponsoredMoneyModel.objects.filter(project__id=project_id, grant__id=grant_id)


MEMBER_STATUS_CHOICES = [
    ('школьник', 'школьник'),
    ('студент', 'студент'),
]

MEMBER_GRADE_CHOICES = [
    ('7 класс', '7 класс'),
    ('8 класс', '8 класс'),
    ('9 класс', '9 класс'),
    ('10 класс', '10 класс'),
    ('11 класс', '11 класс'),

    ('1 курс ', '1 курс'),
    ('2 курс', '2 курс'),
    ('3 курс', '3 курс'),
    ('4 курс', '4 курс'),

]


class MemberModel(models.Model):
    first_name = models.CharField()
    second_name = models.CharField()
    last_name = models.CharField()

    status = models.CharField(choices=MEMBER_STATUS_CHOICES, blank=False, null=False)

    team = models.ForeignKey(TeamModel, on_delete=models.PROTECT, blank=True, null=True)

    email = models.EmailField()
    phone = models.CharField()
    tg_username = models.CharField()

    date_of_birth = models.DateField(blank=False, null=True)
    city = models.CharField()
    school = models.CharField()
    grade = models.CharField(choices=MEMBER_GRADE_CHOICES, blank=True, null=True, default=None)
    subjects = models.CharField(blank=False, null=True)
    languages = models.TextField(blank=False, null=True, default="Русский - родной")

    skills = models.TextField(blank=False, null=True)
    hobbies = models.TextField(blank=False, null=True)
    achievements = models.TextField(blank=False, null=True)

    more_info = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.second_name} {self.last_name}"

    def get_full_name(self):
        return f"{self.first_name} {self.second_name} {self.last_name}"

    def get_username(self):
        return self.tg_username.replace('@', '')

    def get_all_info(self):
        return {
            'статус': self.status,
            'совет': self.team,
            'email': self.email,
            'телефон': self.phone,
            'дата рождения': self.date_of_birth,
            'город проживания': self.city,
            'образование': self.school,
            'класс/курс': self.grade if self.grade else "-",
            'учебная сфера интересов': self.subjects,
            'Иностранные языки': self.languages,
            'навыки': self.skills,
            'увлечения': self.hobbies,
            'достижения': self.achievements,
            'доп. информация': self.more_info,
        }

    @staticmethod
    def get_team_members(team_name):
        return MemberModel.objects.filter(team__name=team_name)

    @staticmethod
    def get_team_member_num(team_name):
        return MemberModel.objects.filter(team__name=team_name).count()

projects/forms.py
from django.forms import ModelForm, Select

from projects.models import ProjectModel, SponsoredMoneyModel


class NewProjectForm(ModelForm):
    class Meta:
        model = ProjectModel
        fields = ['name', 'description', 'by_team', 'manager', 'author', 'period_type', 'start_date', 'end_date',
                  'status']
        widgets = {
            'period_type': Select(choices=ProjectModel.PERIOD_TYPE_CHOICES),
        }


class NewSponsoredMoneyForm(ModelForm):
    class Meta:
        model = SponsoredMoneyModel
        fields = ['grant',
                  'money', ]

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewProjectForm, NewSponsoredMoneyForm
from django.db.models.deletion import ProtectedError
from .models import ProjectModel, SponsoredMoneyModel


def all_projects(request):
    projects = ProjectModel.objects.all()
    return render(request, 'projects/all_projects.html', {'projects': projects})


def edit_project(request, project_id):
    project = get_object_or_404(ProjectModel, pk=project_id)
    if request.method == 'POST':
        form = NewProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('project:specific_project', project_id=project_id)
    else:
        form = NewProjectForm(instance=project)

    return render(request, 'projects/edit_project.html', {'form': form, 'project': project})


def specific_project(request, project_id):
    project = get_object_or_404(ProjectModel, pk=project_id)
    return render(request, 'projects/specific_project.html', {'project': project})


def add_new_project(request):
    if request.method == 'GET':
        return render(request, 'projects/add_new_project.html', {'form': NewProjectForm})
    else:
        try:
            form = NewProjectForm(request.POST)
            new_project = form.save(commit=False)
            new_project.save()
            return redirect('project:all_projects')
        except ValueError:
            return render(request, 'projects/add_new_project.html',
                          {'form': NewProjectForm(), 'error': 'Что-то заполнено не так'})
        except IndentationError:
            return render(request, 'projects/add_new_project.html',
                          {'form': NewProjectForm(), 'error': 'Проект с таким названием уже существует'})


def delete_project(request, project_id):
    project = get_object_or_404(ProjectModel, pk=project_id)
    projects = ProjectModel.objects.all()
    try:
        if request.method == 'POST':
            project.delete()
            return redirect('project:all_projects')
        else:
            return render(request, 'projects/all_projects.html', {'projects': projects})
    except ProtectedError as e:
        return render(request, 'projects/specific_project.html',
                      {'project': project,
                       'error': 'Нельзя удалить проект до тех пор, пока существуют гранты, в которых проект участвовал.\n'
                                'Для удаления проекта необходимо удалить записи о полученных средствах в рамках грантов, в которых участвовал проект.\n'
                                'Для этого необходимо перейти на страницу грантов, открыть страницу конкретного гранта, в котором участвовал проект,'
                                ' и удалить записи о полученных средствах (там справа напротив каждого участвовавшего проекта есть кнопочка корзины).'})
    except Exception as e:
        print(e, type(e))
        return render(request, 'projects/specific_project.html', {'project': project,
                                                                  'error': 'почему-то не удаляется :(\n''айтишник посредственный оказался'})


def add_sponsored_money(request, project_id):
    projects = ProjectModel.objects.all()
    if request.method == 'GET':
        return render(request, 'projects/add_sponsored_money.html', {'form': NewSponsoredMoneyForm})
    else:
        form = NewSponsoredMoneyForm(request.POST)
        try:
            new_project = form.save(commit=False)
            new_project.project = ProjectModel.objects.get(pk=project_id)
            new_project.save()
            return redirect('project:specific_project', project_id=project_id)
        except ValueError:
            return render(request, 'projects/all_projects.html',
                          {'projects': projects, 'error': form.errors})
        except IndentationError:
            return render(request, 'projects/all_projects.html',
                          {'projects': projects, 'error': form.errors})


def edit_sponsored_money(request, project_id, grant_id, to_page='project:specific_project'):
    models = SponsoredMoneyModel.get_model_by_project_and_grant(project_id, grant_id)
    if not models:
        raise AssertionError("BEDA")
    sponsored_money = models[0]
    if request.method == 'POST':
        form = NewSponsoredMoneyForm(request.POST, instance=sponsored_money)
        if form.is_valid():
            form.save()
            if 'project' in to_page:
                return redirect(to_page, project_id=project_id)
            else:
                return redirect(to_page, grant_id=grant_id)
    else:
        form = NewSponsoredMoneyForm(instance=sponsored_money)

    return render(request, 'projects/edit_sponsored_money.html', {'form': form, 'sponsored_money': sponsored_money})


def delete_sponsored_money(request, project_id, grant_id, to_page='project:specific_project'):
    models = SponsoredMoneyModel.get_model_by_project_and_grant(project_id, grant_id)
    if not models:
        raise AssertionError("BEDA")
    sponsored_money = models[0]
    try:
        if request.method == 'POST':
            sponsored_money.delete()
            if 'project' in to_page:
                return redirect(to_page, project_id=project_id)
            else:
                return redirect(to_page, grant_id=grant_id)
        else:
            return render(request, 'projects/specific_project.html', {'sponsored_money': sponsored_money})
    except Exception:
        return render(request, 'projects/specific_project.html', {'sponsored_money': sponsored_money,
                                                                  'error': 'почему-то не удаляется :(\n''айтишник посредственный оказался'})

projects/templates/projects/add_new_project.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Add new project</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
<form method="POST">
    {% csrf_token %}
    <h1>Новый проект</h1>

    <label for="name">Название:</label>
    <input type="text" id="name" name="name" required>

    <label for="description">Описание:</label>
    <textarea id="description" name="description" rows="4" required></textarea>

    <label for="by_team">Совет-реализатор:</label>
    {{ form.by_team }}

    <label for="manager">Руководитель:</label>
    {{ form.manager }}

    <label for="manager">Автор:</label>
    {{ form.author }}

    <label for="period_type">Продолжительность:</label>
    {{ form.period_type }}

    <label for="start_date">Дата начала реализации:</label>
    <input type="date" id="start_date" name="start_date" required>

    <label for="status">Отметить как завершенный:</label>
    <input type="checkbox" id="status" name="status">

    <label for="end_date" id="endDateLabel" style="display: none;">Дата окончания реализации:</label>
    <input type="date" id="end_date" name="end_date" style="display: none;">

    <script>
        var statusInput = document.getElementById('status');
        var endDateLabel = document.getElementById('endDateLabel');
        var endDate = document.getElementById('end_date');

        statusInput.addEventListener('change', function () {
            endDateLabel.style.display = statusInput.checked ? 'block' : 'none';
            endDate.style.display = statusInput.checked ? 'block' : 'none';
        });
    </script>

    <button type="submit">Добавить</button>
</form>
</body>

</html>

projects/templates/projects/specific_project.html
<!-- your_template.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ project.name }}</title>
    <style>
        .table-container {
            margin: 20px; /* Add margin around the table */
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        h2 {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        body, html {
        {#height: 100%;#} margin: 0;
        }

        .container {
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 10vh;
            background: #dcdcdc; /* Light gray background */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .nav-link-custom {
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s;
            background-color: #798083; /* Blue background */
            color: white; /* White text */
        }

        .nav-link:hover {
            background-color: #798083; /* Blue background on hover */
            color: white; /* White text on hover */
        }

        .nav-link {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            word-wrap: break-word;
        }

        .logout-btn {
            color: #333; /* Dark gray text color */
            font-size: 20px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            border: none;
            background-color: transparent; /* Transparent background */
            transition: background-color 0.3s;
        }

        .logout-btn:hover {
            background-color: #798083; /* Red background on hover */
            color: white; /* White text on hover */
        }

        .add-btn,
        .edit-btn,
        .delete-btn {
            display: inline-block;
            padding: 7px 50px; /* Увеличенная ширина, уменьшенная высота */
            background-color: #798083; /* Более темный цвет фона */
            color: white; /* Белый текст */
            font-size: 18px;
            font-family: Inter, serif;
            font-weight: 400;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            margin-left: 20px;
            border: none;
        }


        .add-btn:hover,
        .edit-btn:hover,
        .delete-btn:hover {
            background-color: #dcdcdc; /* Цвет фона при наведении */
            color: #333; /* Черный текст при наведении */
        }

        .project-name {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .project-container {
            display: flex;
            align-items: center; /* Центрирование по вертикали */
            justify-content: space-around;
        }

        .project-description,
        .status-description {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: left;
            background-color: #f2f2f2;
            padding: 20px;
            border-radius: 10px;
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center; /* Центрирование по горизонтали */
            justify-content: center; /* Центрирование по вертикали */
        }

        .project-description {
            margin-left: 10%;
            margin-right: 10%;
        }

        .status-description {
            margin-top: 20px;
            margin-right: 10%;
            margin-bottom: 20px;
        }


        .project-manager {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: left;
            margin-left: 10%;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .project-grants-info {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: left;
            margin-left: 20px;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .error-message {
            font-family: Inter, serif;
            font-weight: 400;
            font-size: 20px;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 20px;
            color: red;
        }

    </style>
</head>


{% block content %}

    <div class="container">
        <a class="nav-link" href="{% url 'team:all_teams' %}">Советы</a>
        <a class="nav-link-custom" href="{% url 'project:all_projects' %}">Проекты</a>
        <a class="nav-link" href="{% url 'grant:all_grants' %}">Гранты</a>
        <a class="nav-link" href="{% url 'members:all_members' %}">Участники</a>
        {% if user.is_authenticated %}
            <form action="{% url 'logoutuser' %}" method="POST">
                {% csrf_token %}
                <input class="logout-btn" type="submit" value="Logout">
            </form>
        {% else %}
            <a class="nav-link" href="{% url 'loginuser' %}">Login</a>
        {% endif %}
    </div>


    <div class="project-name">
        <h1>{{ project.name }}</h1>
    </div>

    <div class="project-container">

        <div class="project-description">
            {{ project.description }}
        </div>

        <div class="status-description">
            {% if not project.status %}
                Статус: в реализации
                {% if project.start_date %}
                    <br>
                    <div>{{ project.start_date|date:"d.m.Y" }} - н.в.</div>
                {% endif %}
            {% else %}
                Статус: завершен
                {% if project.start_date and project.end_date %}
                    <br>
                    <div>{{ project.start_date|date:"d.m.Y" }} - {{ project.end_date|date:"d.m.Y" }}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="project-manager">
        <p>Руководитель проекта: {{ project.manager }}</p>
    </div>


    <body>
    <h2>Общая информация</h2>
    <div class="table-container">
        <table>
            <tr>
                <th>Совет-реализатор</th>
                <th>Автор проекта</th>
                <th>Продолжительность</th>
                <th>Средств получено</th>
            </tr>
            <tr>
                <td><a href="{% url 'team:specific_team' project.by_team.id %}">{{ project.by_team }}</a></td>
                <td>{{ project.author }}</td>
                <td>{{ project.period_type }}</td>
                <td>{{ project.get_sponsored_money }}₽</td>
            </tr>
        </table>
    </div>

    <p>
        <a class="edit-btn" href="{% url 'project:edit_project' project.id %}">Редактировать</a>
    </p>
    <form method="POST" action="{% url 'project:delete_project' project.id %}">
        {% csrf_token %}
        <button type="submit" class="delete-btn">Удалить</button>
        {% if error %}
            <div class="error-message"><p>{{ error }}</p></div>
        {% endif %}
    </form>

    <h2>Выигранные гранты</h2>
    {% if project.get_sponsored_money == 0 %}

        <div class="project-grants-info">
            <p>У проекта пока нет выигранных грантов</p>
        </div>
    {% else %}

        <div class="table-container">
            <table>
                <tr>
                    <th>Грант</th>
                    <th>Средств получено</th>
                </tr>
                {% for grant, sum_ in project.get_sponsored_money_from_all_grants.items %}
                    {% if sum_ != 0 and sum_ != 'не подавали' %}
                        <tr>
                            <td><a href="{% url 'grant:specific_grant' grant.id %}">{{ grant.name }}</a></td>
                            <td>{{ sum_ }}₽</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </table>
        </div>
    {% endif %}

    <p>
        <a class="add-btn" href="{% url 'project:add_sponsored_money' project.id %}">Добавить грант</a>
    </p>
    <p></p>
    </body>
{% endblock %}
</html>